### PR TITLE
fix: Fixed parse error message and type filter example

### LINKED ISSUE #244: Out of date example for formatting output
In the examples section of the `tick log -h`, it still uses `-f` for formatting output instead of the newer `-t`.

screen shot 2016-07-29 at 9 26 33 am

### PR DESCRIPTION
**Pull request by sofia-scho**
Resolves #244 and #211

### CODE REVIEW

File: src/commands/tick-log.js [hunk 1]
```diff
@@ -58,7 +62,14 @@ function log(argv) {
       break
   }
 }
-
+function writeFilterError() {
```
Comment (chadfawcett) [inline src/commands/tick-log.js]: @sofia-scho could you add a blank line above and below this function? We want to try and keep the code looking consistent with the other functions.

Comment (sofia-scho) [inline src/commands/tick-log.js]: Yup👍

**Comment by chadfawcett** [comment]
@sofia-scho I just made the one comment about the code styling. Once that's been fixed feel free to merge this in. 👍
